sources/backend/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from backend import settings
from core import views as core_views
from core.views import RegisterView, LoginView

urlpatterns = [  # Homepage
                  path('', core_views.index, name='home'),

                  # Auth route
                  path('login', LoginView.as_view(), name="login"),
                  path('register', RegisterView.as_view(), name="register"),
                  path('logout', core_views.logout, name="logout"),

                  # Dashboard
                  path('dashboard', core_views.index, name="dashboard"),
                  # Follows
                  path('follows', include('following.urls')),

                  # Tickets
                  path('tickets/', include('reviewing.urls')),

                  # Feed
                  path('feed', include('feed.urls')),

                  # Admin
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sources/feed/urls.py
from django.urls import path

from .views import FeedView

urlpatterns = [
    path('', FeedView.as_view(), name="feed.index"),
]

sources/following/urls.py
from django.urls import path

from .views import index, unfollow

urlpatterns = [
    path('', index, name="following.index"),
    path('<str:username>', unfollow, name="following.unfollow"),
]

sources/following/models.py
from django.conf import settings
from django.db import models
from django.db.models import Manager


class UserFollows(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="following")
    followed_user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="followed_by")

    objects = Manager()
    
    class Meta:
        unique_together = ('user', 'followed_user')

sources/following/forms/FollowUserForm.py
from django import forms


class FollowUserForm(forms.Form):
    followed_user = forms.ChoiceField(
        label='Followed user',
    )

    def __init__(self, *args, choices):
        super().__init__(*args)
        self.fields['followed_user'].choices = choices

sources/following/views.py
from django.db.models import Exists, OuterRef
from django.http import HttpRequest
from django.shortcuts import render, redirect

from core.models import User
from following.forms.FollowUserForm import FollowUserForm
from following.models import UserFollows


def index(request: HttpRequest):
    followings = User.objects \
        .exclude(id=request.user.id) \
        .filter(Exists(UserFollows.objects.filter(user=request.user, followed_user_id=OuterRef('id'))))

    followers = User.objects \
        .exclude(id=request.user.id) \
        .filter(Exists(UserFollows.objects.filter(user_id=OuterRef('id'), followed_user=request.user)))

    followables = User.objects.exclude(id=request.user.id) \
        .filter(~Exists(UserFollows.objects.filter(user=request.user, followed_user_id=OuterRef('id'))))

    form = FollowUserForm(choices=[(u.username, u.username) for u in followables])

    if request.method == "POST":
        form = FollowUserForm(request.POST, choices=[(u.username, u.username) for u in followables])
        if form.is_valid():
            follow = UserFollows()
            follow.followed_user = User.objects.get(username=form.cleaned_data.get('followed_user'))
            follow.user = request.user
            follow.save()
            return redirect("following.index")

    return render(request, "following/index.html",
                  context={'form': form, 'followings': followings, 'followers': followers})


def unfollow(request: HttpRequest, username: str):
    follow = UserFollows.objects.filter(user=request.user, followed_user=User.objects.get(username=username))
    follow.delete()
    return redirect("following.index")

sources/following/templates/following/index.html
{% extends "core/_layout.html" %}
{% block title %}Abonnements{% endblock %}
{% block head %}
    <style>
        select#id_followed_user {
            width: 100%;
        }
    </style>
{% endblock %}
{% block content %}
    <section id="follow" class="px-2 md:px-8 mb-4">
        <h2 class="font-roboto-slab text-primary text-2xl font-[500] text-center mb-4">
            Suivre d'autres utilisateurs
        </h2>
        <form action="{% url "following.index" %}" method="POST" class="inline-flex w-full">
            {% csrf_token %}
            {{ form.followed_user }}
            <button type="submit"
                    class="px-4 py-2 bg-primary text-white rounded-md hover:bg-secondary transition-colors ml-4">
                Envoyer
            </button>
        </form>
    </section>

    {% if followings|length > 0 %}
        <section id="follow" class="px-2 md:px-8 mb-4">
            <h2 class="font-roboto-slab text-primary text-2xl font-[500] text-center mb-4">
                Abonnements
            </h2>

            {% for following in followings %}
                <div class="flex border border-secondary  pl-4">
                    <span class="w-full py-2">{{ following.username }}</span>
                    <a href="{% url "following.unfollow" following.username %}"
                       class="hover:bg-primary bg-secondary text-white py-2 px-4 transition-colors">
                        Désabonner
                    </a>
                </div>
            {% endfor %}
        </section>
    {% endif %}

    {% if followers|length > 0 %}
        <section id="follow" class="px-2 md:px-8 mb-4">
            <h2 class="font-roboto-slab text-primary text-2xl font-[500] text-center mb-4">
                Abonnés
            </h2>

            {% for follower in followers %}
                <div class="flex border border-primary py-2 px-4 w-full">
                    {{ follower.username }}
                </div>
            {% endfor %}
        </section>
    {% endif %}

{% endblock %}